# This is a config for E2B sandbox template.
# You can use template ID (pk4i68cehvpwr7vaka7z) or template name (swiftly) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("swiftly") # Sync sandbox
# sandbox = await AsyncSandbox.create("swiftly") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('swiftly')

team_id = "03b36467-cf8f-4f02-b007-89a177be557a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "swiftly"
template_id = "pk4i68cehvpwr7vaka7z"
